#=============================================================================#
# ARM makefile for the uC-CPU lib
# 
# author      : Xavier Meyer
# last change : 2010-01-08
#
#=============================================================================#

# C headers
DIR_HEADERS += ./uC-CPU/
DIR_HEADERS += ./uC-CPU/Cortex-M3/GCC/

# C sources
LIST_SOURCES += ./uC-CPU/Cortex-M3/GCC/cpu_c.c

# Assembler files
LIST_ASM += ./uC-CPU/Cortex-M3/GCC/cpu_a.asm

#vpath %.c ./uC-CPU/Cortex-M3/GCC/
#vpath %.asm ./uC-CPU/Cortex-M3/GCC/
