#=============================================================================#
# ARM makefile for the STM32F10x USB-FS-Device_Driver
# 
# author      : Xavier Meyer
# last change : 2010-01-26
# misc.		  : otgd_fs (on the go) are not added currently because not used
#
#=============================================================================#

# C headers
DIR_HEADERS += ./STM32_USB-FS-Device_Driver/inc/

# C sources
LIST_SOURCES += ./STM32_USB-FS-Device_Driver/src/usb_core.c
LIST_SOURCES += ./STM32_USB-FS-Device_Driver/src/usb_init.c
LIST_SOURCES += ./STM32_USB-FS-Device_Driver/src/usb_int.c
LIST_SOURCES += ./STM32_USB-FS-Device_Driver/src/usb_mem.c
LIST_SOURCES += ./STM32_USB-FS-Device_Driver/src/usb_regs.c
LIST_SOURCES += ./STM32_USB-FS-Device_Driver/src/usb_sil.c


#vpath %.c ./STM32F10x_StdPeriph_Driver/src/

