#=============================================================================#
# ARM makefile for the STM32F10x std Periph Driver
# 
# author      : Xavier Meyer
# last change : 2010-01-08
# misc.		  : To add others STM32F10x periph you must add the source files
#				to the list of sources
#
#=============================================================================#

# C headers
DIR_HEADERS += ./STM32F10x_StdPeriph_Driver/inc/

# C sources
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/misc.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c
LIST_SOURCES += ./STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c

#vpath %.c ./STM32F10x_StdPeriph_Driver/src/

