#=============================================================================#
# ARM makefile for the CMSIS lib
# 
# author: Xavier Meyer
# last change: 2010-01-08
#
#=============================================================================#

# C headers
DIR_HEADERS += ./CMSIS/Core/CM3/

# C sources
# LIST_SOURCES += ./Core/CM3/core_cm3.c
# LIST_SOURCES += ./Core/CM3/system_stm32f10x.c
